services:
    mws_barcode.generator:
        class: MWSimple\BarcodeBundle\Generator\Generator

    mws_barcode.twig.extension:
        class: MWSimple\BarcodeBundle\Twig\Extensions\Barcode
        arguments:
            - @mws_barcode.generator
        tags:
            - { name: twig.extension }
